#!/bin/bash
# WF 2022-09-03
# start sqlite web browser for EventCorpus.db
which sqlite_web
if [ $? -ne 0 ]
then
  pip install sqlite-web
fi
cd $HOME/.conferencecorpus
pgrep -fl "sqlite_web EventCorpus.db" > /dev/null
if [ $? -eq 0 ]
then
  echo "killing existing sqlite_web EventCorpus.db"
  pkill -f "sqlite_web EventCorpus.db" > /dev/null
fi
nohup sqlite_web EventCorpus.db&
sleep 0.5
tail -f nohup.out
