#!/bin/bash
# WF 2021-07-31
# get the offline data
base=$HOME/.conferencecorpus
mkdir $base
cd $base
for tgz in wikicfp crossref
do
   # download 
   curl -s https://github.com/WolfgangFahl/ConferenceCorpus/wiki/data/$tgz.tgz -o $tgz.tgz
   # unpack and unzip
   tar xvfz $tgz.tgz
done
